"""initial_schema

Revision ID: 618dcdadc091
Revises: 
Create Date: 2026-07-17 11:28:10.377360
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "618dcdadc091"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("automation_log",
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("job_name", sa.String(length=128), nullable=False),
    sa.Column("channel_id", sa.Integer(), nullable=True),
    sa.Column("triggered_at", sa.DateTime(), nullable=False),
    sa.Column("status", sa.String(length=32), nullable=False),
    sa.Column("error_message", sa.Text(), nullable=True),
    sa.Column("result_count", sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("games",
    sa.Column("id", sa.String(length=255), nullable=False),
    sa.Column("title", sa.String(length=512), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column("short_description", sa.String(length=1024), nullable=True),
    sa.Column("genres", sa.JSON(), nullable=False),
    sa.Column("tags", sa.JSON(), nullable=False),
    sa.Column("platforms", sa.JSON(), nullable=False),
    sa.Column("developers", sa.JSON(), nullable=False),
    sa.Column("publishers", sa.JSON(), nullable=False),
    sa.Column("release_date", sa.Date(), nullable=True),
    sa.Column("coming_soon_date", sa.Date(), nullable=True),
    sa.Column("steam_app_id", sa.Integer(), nullable=True),
    sa.Column("epic_namespace", sa.String(length=255), nullable=True),
    sa.Column("gog_id", sa.String(length=255), nullable=True),
    sa.Column("cover_url", sa.String(length=1024), nullable=True),
    sa.Column("banner_url", sa.String(length=1024), nullable=True),
    sa.Column("metacritic_score", sa.Integer(), nullable=True),
    sa.Column("steam_review_score", sa.Float(), nullable=True),
    sa.Column("steam_review_count", sa.Integer(), nullable=True),
    sa.Column("provider_name", sa.String(length=128), nullable=False),
    sa.Column("provider_url", sa.String(length=1024), nullable=True),
    sa.Column("is_free", sa.Boolean(), nullable=False),
    sa.Column("free_until", sa.Date(), nullable=True),
    sa.Column("raw_metadata", sa.JSON(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("sales",
    sa.Column("id", sa.String(length=255), nullable=False),
    sa.Column("title", sa.String(length=512), nullable=False),
    sa.Column("event_type", sa.String(length=64), nullable=False),
    sa.Column("store", sa.String(length=64), nullable=True),
    sa.Column("starts_at", sa.DateTime(), nullable=False),
    sa.Column("ends_at", sa.DateTime(), nullable=True),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column("url", sa.String(length=1024), nullable=True),
    sa.Column("calendar_event_id", sa.String(length=255), nullable=True),
    sa.Column("reminder_minutes", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_table("user_preferences",
    sa.Column("discord_user_id", sa.Integer(), nullable=False),
    sa.Column("favorite_genres", sa.JSON(), nullable=False),
    sa.Column("ignored_stores", sa.JSON(), nullable=False),
    sa.Column("ignored_tags", sa.JSON(), nullable=False),
    sa.Column("surprise_history", sa.JSON(), nullable=False),
    sa.Column("discount_threshold", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("updated_at", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("discord_user_id")
    )
    op.create_table("deals",
    sa.Column("id", sa.String(length=255), nullable=False),
    sa.Column("game_id", sa.String(length=255), nullable=True),
    sa.Column("title", sa.String(length=512), nullable=False),
    sa.Column("store", sa.String(length=64), nullable=False),
    sa.Column("store_url", sa.String(length=1024), nullable=True),
    sa.Column("currency", sa.String(length=16), nullable=False),
    sa.Column("current_price", sa.Float(), nullable=False),
    sa.Column("original_price", sa.Float(), nullable=True),
    sa.Column("discount_percent", sa.Float(), nullable=False),
    sa.Column("historical_low_price", sa.Float(), nullable=True),
    sa.Column("is_historical_low", sa.Boolean(), nullable=False),
    sa.Column("deal_started_at", sa.DateTime(), nullable=True),
    sa.Column("deal_ends_at", sa.DateTime(), nullable=True),
    sa.Column("provider_names", sa.JSON(), nullable=False),
    sa.Column("is_free", sa.Boolean(), nullable=False),
    sa.Column("free_until", sa.Date(), nullable=True),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(["game_id"], ["games.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("deals")
    op.drop_table("user_preferences")
    op.drop_table("sales")
    op.drop_table("games")
    op.drop_table("automation_log")
    # ### end Alembic commands ###
